/*
 * Omaha
 *
 * Simplified Omaha server in Rust
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestPing struct {
	R int32 `json:"r,omitempty"`
}
