/*
 * Omaha
 *
 * Simplified Omaha server in Rust
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Request struct {
	Protocal float64 `json:"protocal,omitempty"`
	Version float64 `json:"version,omitempty"`
	Ismachine int32 `json:"ismachine,omitempty"`
	Sessionid string `json:"sessionid,omitempty"`
	Userid string `json:"userid,omitempty"`
	Installsource string `json:"installsource,omitempty"`
	Testsource string `json:"testsource,omitempty"`
	Requestid string `json:"requestid,omitempty"`
	Hw *RequestHw `json:"hw,omitempty"`
	Os *RequestOs `json:"os,omitempty"`
	App []App `json:"app,omitempty"`
	Updatecheck *interface{} `json:"updatecheck,omitempty"`
	Ping *RequestPing `json:"ping,omitempty"`
}
