/*
 * Omaha
 *
 * Simplified Omaha server in Rust
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type App struct {
	Appid string `json:"appid,omitempty"`
	// check type
	Version string `json:"version,omitempty"`
	// check if needs to be nillable
	Nextversion string `json:"nextversion,omitempty"`
	// check languages
	Lang string `json:"lang,omitempty"`
	Brand string `json:"brand,omitempty"`
	Client string `json:"client,omitempty"`
	Installage int32 `json:"installage,omitempty"`
}
