/*
 * Omaha
 *
 * Simplified Omaha server in Rust
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RequestOs struct {
	Platform string `json:"platform,omitempty"`
	Version float64 `json:"version,omitempty"`
	// check what this is
	Sp string `json:"sp,omitempty"`
	Arch string `json:"arch,omitempty"`
}
